# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'twitterdash.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Mw_TwitteDash(object):
    def setupUi(self, Mw_TwitteDash):
        Mw_TwitteDash.setObjectName("Mw_TwitteDash")
        Mw_TwitteDash.setEnabled(True)
        Mw_TwitteDash.resize(1260, 699)
        self.centralwidget = QtWidgets.QWidget(Mw_TwitteDash)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_ReadCredentials = QtWidgets.QWidget(self.centralwidget)
        self.widget_ReadCredentials.setGeometry(QtCore.QRect(20, 50, 821, 311))
        self.widget_ReadCredentials.setObjectName("widget_ReadCredentials")
        self.Label_ConKey = QtWidgets.QLabel(self.widget_ReadCredentials)
       
        #Added to hide the widget for later call
        self.widget_ReadCredentials.hide()
        
        self.Label_ConKey.setGeometry(QtCore.QRect(52, 49, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Label_ConKey.setFont(font)
        self.Label_ConKey.setObjectName("Label_ConKey")
        self.Label_ConSec = QtWidgets.QLabel(self.widget_ReadCredentials)
        self.Label_ConSec.setGeometry(QtCore.QRect(49, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Label_ConSec.setFont(font)
        self.Label_ConSec.setObjectName("Label_ConSec")
        self.Label_AccKey = QtWidgets.QLabel(self.widget_ReadCredentials)
        self.Label_AccKey.setGeometry(QtCore.QRect(50, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Label_AccKey.setFont(font)
        self.Label_AccKey.setObjectName("Label_AccKey")
        self.Label_AccKey_2 = QtWidgets.QLabel(self.widget_ReadCredentials)
        self.Label_AccKey_2.setGeometry(QtCore.QRect(50, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Label_AccKey_2.setFont(font)
        self.Label_AccKey_2.setObjectName("Label_AccKey_2")
        self.pTE_ConKey = QtWidgets.QPlainTextEdit(self.widget_ReadCredentials)
        self.pTE_ConKey.setGeometry(QtCore.QRect(190, 50, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pTE_ConKey.setFont(font)
        self.pTE_ConKey.setObjectName("pTE_ConKey")
        self.pTE_ConSec = QtWidgets.QPlainTextEdit(self.widget_ReadCredentials)
        self.pTE_ConSec.setGeometry(QtCore.QRect(190, 90, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pTE_ConSec.setFont(font)
        self.pTE_ConSec.setObjectName("pTE_ConSec")
        self.pTE_AccKey = QtWidgets.QPlainTextEdit(self.widget_ReadCredentials)
        self.pTE_AccKey.setGeometry(QtCore.QRect(190, 130, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pTE_AccKey.setFont(font)
        self.pTE_AccKey.setObjectName("pTE_AccKey")
        self.pTE_AccSec = QtWidgets.QPlainTextEdit(self.widget_ReadCredentials)
        self.pTE_AccSec.setGeometry(QtCore.QRect(190, 170, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pTE_AccSec.setFont(font)
        self.pTE_AccSec.setObjectName("pTE_AccSec")
        self.pB_LdCred = QtWidgets.QPushButton(self.widget_ReadCredentials)
        self.pB_LdCred.setGeometry(QtCore.QRect(190, 230, 111, 28))
        self.pB_LdCred.setObjectName("pB_LdCred")
        self.pB_CredFile_2 = QtWidgets.QPushButton(self.widget_ReadCredentials)
        self.pB_CredFile_2.setGeometry(QtCore.QRect(640, 230, 111, 28))
        self.pB_CredFile_2.setObjectName("pB_CredFile_2")
        self.pB_LdCred_2 = QtWidgets.QPushButton(self.widget_ReadCredentials)
        self.pB_LdCred_2.setGeometry(QtCore.QRect(310, 230, 111, 28))
        self.pB_LdCred_2.setObjectName("pB_LdCred_2")
        self.pB_LdCred_3 = QtWidgets.QPushButton(self.widget_ReadCredentials)
        self.pB_LdCred_3.setGeometry(QtCore.QRect(430, 230, 121, 28))
        self.pB_LdCred_3.setObjectName("pB_LdCred_3")
        Mw_TwitteDash.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mw_TwitteDash)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1260, 26))
        self.menubar.setObjectName("menubar")
        self.menuTwitter_Dash = QtWidgets.QMenu(self.menubar)
        self.menuTwitter_Dash.setObjectName("menuTwitter_Dash")
        self.menuFriends = QtWidgets.QMenu(self.menubar)
        self.menuFriends.setObjectName("menuFriends")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Mw_TwitteDash.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Mw_TwitteDash)
        self.statusbar.setObjectName("statusbar")
        Mw_TwitteDash.setStatusBar(self.statusbar)
        self.actionRead_Authentication_File = QtWidgets.QAction(Mw_TwitteDash)
        self.actionRead_Authentication_File.setObjectName("actionRead_Authentication_File")
        
        #Show Read Credentials Widgets After Click Option
        self.actionRead_Authentication_File.triggered.connect(lambda: self.widget_ReadCredentials.show())
        
        self.actionTwitter_Bot_Settings = QtWidgets.QAction(Mw_TwitteDash)
        self.actionTwitter_Bot_Settings.setObjectName("actionTwitter_Bot_Settings")
        self.actionTwitter_Auto_Follow_Request = QtWidgets.QAction(Mw_TwitteDash)
        self.actionTwitter_Auto_Follow_Request.setObjectName("actionTwitter_Auto_Follow_Request")
        self.actionTrending_Topics_Settings = QtWidgets.QAction(Mw_TwitteDash)
        self.actionTrending_Topics_Settings.setObjectName("actionTrending_Topics_Settings")
        self.actionSecurity = QtWidgets.QAction(Mw_TwitteDash)
        self.actionSecurity.setObjectName("actionSecurity")
        self.actionExit = QtWidgets.QAction(Mw_TwitteDash)
        self.actionExit.setObjectName("actionExit")
        self.actionBot_File_Keys = QtWidgets.QAction(Mw_TwitteDash)
        self.actionBot_File_Keys.setObjectName("actionBot_File_Keys")
        self.actionAbout = QtWidgets.QAction(Mw_TwitteDash)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCreate_Followers_File = QtWidgets.QAction(Mw_TwitteDash)
        self.actionCreate_Followers_File.setObjectName("actionCreate_Followers_File")
        self.actionCreate_Following_Files = QtWidgets.QAction(Mw_TwitteDash)
        self.actionCreate_Following_Files.setObjectName("actionCreate_Following_Files")
        self.actionRead_Followers_File = QtWidgets.QAction(Mw_TwitteDash)
        self.actionRead_Followers_File.setObjectName("actionRead_Followers_File")
        self.actionRead_Following_File = QtWidgets.QAction(Mw_TwitteDash)
        self.actionRead_Following_File.setObjectName("actionRead_Following_File")
        self.actionStatistics = QtWidgets.QAction(Mw_TwitteDash)
        self.actionStatistics.setObjectName("actionStatistics")
        self.actionBot_File_Keys_2 = QtWidgets.QAction(Mw_TwitteDash)
        self.actionBot_File_Keys_2.setObjectName("actionBot_File_Keys_2")
        self.actionAbout_2 = QtWidgets.QAction(Mw_TwitteDash)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.menuTwitter_Dash.addAction(self.actionRead_Authentication_File)
        self.menuTwitter_Dash.addAction(self.actionTwitter_Bot_Settings)
        self.menuTwitter_Dash.addAction(self.actionTwitter_Auto_Follow_Request)
        self.menuTwitter_Dash.addAction(self.actionTrending_Topics_Settings)
        self.menuTwitter_Dash.addAction(self.actionSecurity)
        self.menuTwitter_Dash.addSeparator()
        self.menuTwitter_Dash.addAction(self.actionExit)
        self.menuFriends.addAction(self.actionCreate_Followers_File)
        self.menuFriends.addAction(self.actionCreate_Following_Files)
        self.menuFriends.addAction(self.actionRead_Followers_File)
        self.menuFriends.addAction(self.actionRead_Following_File)
        self.menuFriends.addAction(self.actionStatistics)
        self.menuHelp.addAction(self.actionBot_File_Keys_2)
        self.menuHelp.addAction(self.actionAbout_2)
        self.menubar.addAction(self.menuTwitter_Dash.menuAction())
        self.menubar.addAction(self.menuFriends.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Mw_TwitteDash)
        QtCore.QMetaObject.connectSlotsByName(Mw_TwitteDash)

    def retranslateUi(self, Mw_TwitteDash):
        _translate = QtCore.QCoreApplication.translate
        Mw_TwitteDash.setWindowTitle(_translate("Mw_TwitteDash", "Twitter Dash"))
        self.Label_ConKey.setText(_translate("Mw_TwitteDash", "Consumer Key"))
        self.Label_ConSec.setText(_translate("Mw_TwitteDash", "Consumer Secret"))
        self.Label_AccKey.setText(_translate("Mw_TwitteDash", "Access Key"))
        self.Label_AccKey_2.setText(_translate("Mw_TwitteDash", "Access Secret"))
        self.pB_LdCred.setText(_translate("Mw_TwitteDash", "Load Credentials"))
        self.pB_CredFile_2.setText(_translate("Mw_TwitteDash", "Authenticate"))
        self.pB_LdCred_2.setText(_translate("Mw_TwitteDash", "Save Credentials"))
        self.pB_LdCred_3.setText(_translate("Mw_TwitteDash", "Delete Credentials"))
        self.menuTwitter_Dash.setTitle(_translate("Mw_TwitteDash", "Twitter Dash"))
        self.menuFriends.setTitle(_translate("Mw_TwitteDash", "Friends"))
        self.menuHelp.setTitle(_translate("Mw_TwitteDash", "Help"))
        self.actionRead_Authentication_File.setText(_translate("Mw_TwitteDash", "Authenticate Credentials"))       
        self.actionTwitter_Bot_Settings.setText(_translate("Mw_TwitteDash", "Bot Settings"))
        self.actionTwitter_Auto_Follow_Request.setText(_translate("Mw_TwitteDash", "Auto Follow Settings"))
        self.actionTrending_Topics_Settings.setText(_translate("Mw_TwitteDash", "Trending Topics Settings"))
        self.actionSecurity.setText(_translate("Mw_TwitteDash", "Security"))
        self.actionExit.setText(_translate("Mw_TwitteDash", "Exit"))
        self.actionBot_File_Keys.setText(_translate("Mw_TwitteDash", "Bot File Keys"))
        self.actionAbout.setText(_translate("Mw_TwitteDash", "About"))
        self.actionCreate_Followers_File.setText(_translate("Mw_TwitteDash", "Create Followers File"))
        self.actionCreate_Following_Files.setText(_translate("Mw_TwitteDash", "Create Following Files"))
        self.actionRead_Followers_File.setText(_translate("Mw_TwitteDash", "Read Followers File"))
        self.actionRead_Following_File.setText(_translate("Mw_TwitteDash", "Read Following File"))
        self.actionStatistics.setText(_translate("Mw_TwitteDash", "Statistics"))
        self.actionBot_File_Keys_2.setText(_translate("Mw_TwitteDash", "Bot File Keys"))
        self.actionAbout_2.setText(_translate("Mw_TwitteDash", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mw_TwitteDash = QtWidgets.QMainWindow()
    ui = Ui_Mw_TwitteDash()
    ui.setupUi(Mw_TwitteDash)
    Mw_TwitteDash.show()
    sys.exit(app.exec_())

